### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TonyStark** [rouze-d/tiktok-download#1]
```
$ bash tik.sh "https://www.tiktok.com/@user/video/126546132165"
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

**Comment by rouze-d** [comment]
not work if account is private,
and make sure the URL address is available.

**Comment by TonyStark** [comment]
no
account is not private, and url is accessible
however i did not install lolcat because it looks like not necessary to fetching video

**Comment by rouze-d** [comment]
i just add useragent on curl command.
if it's not working and if you don't mind, you can email link on _freepoint4u@protonmail.com_ and and I will find out..

**Comment by TonyStark** [comment]
ok
will email you
maybe there tiktok improved something because youtube-dl also not working for downloading.

**Comment by TonyStark** [comment]
but i will email you about some information :)
