### ISSUE TITLE
Code looks obfuscated. Why?

### ISSUE THREAD

**Issue by cardoso-neto** [rouze-d/tiktok-download#2]
Care to share an explanation as to why the code looks like that?

**Comment by rouze-d** [comment]
done decrypt that script.
https://github.com/rouze-d/bashrock

**Comment by cardoso-neto** [comment]
Why? Do you seriously expect programmers to run code they can't read on their computers?

Please share a non-obfuscated version of your script. A version without the "encryption".

**Comment by rouze-d** [comment]
[https://mega.nz/file/AypDHAYA#mIZBW5bRSgfz5kuPMkwufQMtKPwfucp2df3vFjgdllY](url)

**Comment by rouze-d** [comment]
https://mega.nz/file/AypDHAYA#mIZBW5bRSgfz5kuPMkwufQMtKPwfucp2df3vFjgdllY

**Comment by cardoso-neto** [comment]
Ok. That's a lot better. You should have *that* up on Github. Not the obfuscated version.
